name = input("Enter your name: ")
age = input("Enter your age: ")
country=input("Enter the country: ")
state=input("Enter the state: ")
city = input("Enter your city: ")
clg = input("Enter your clg name: ")
print("Name:", name)    
print("Age:", age)
print("Country:",country)
print("state:",state)
print("City:", city)
print("Clg:",clg)
